name: Download and Commit File to Repo

on:
  push:
    branches:
      - main

jobs:
  download_and_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download File
        run: |
          curl -O https://alinallmovies.tbnbotsnetwork.workers.dev/26218/Jay+Rox+-+Ma+Shocko.mp3?hash=AgADU1
          
      - name: Commit File to Repo
        env:
          GITHUB_TOKEN: ${{ secrets.H_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Add downloaded file from URL"
          git push
